import { ContentProviderConfig, ContentProviderAuthData, ContentItem, ContentFile, ProviderLogos, ProviderCapabilities, IProvider, AuthType, Instructions, InstructionItem } from "../../interfaces";
import { parsePath } from "../../pathUtils";
import lifeChurchData from "./data.json";
import { LifeChurchData, LifeChurchSeries, LifeChurchUnit, LifeChurchLesson } from "./LifeChurchInterfaces";

/**
 * Life.Church Provider
 *
 * Browses the Life.Church Open Network kids curriculum from a static catalog
 * (src/providers/lifeChurch/data.json) generated by scripts/scrape-lifechurch.ts.
 *
 * Path structure:
 *   /                              -> 4 series (Loop Show, Konnect, Crosstown, Bible Adventure)
 *   /{seriesId}                    -> units within the series
 *   /{seriesId}/{unitId}           -> lessons within the unit
 *   /{seriesId}/{unitId}/{lessonId} -> single video file
 *
 * Video delivery: Life.Church publishes their kids curriculum as YouTube embeds
 * on open.life.church. Each ContentFile.url points at https://www.youtube.com/embed/{id}
 * and providerData.youtubeId carries the raw id for clients that want to render
 * via the YouTube IFrame API. Direct mp4 downloads on open.life.church are
 * auth-gated (/downloads/create/{id}), so we deliberately do NOT attempt to
 * scrape them.
 */
export class LifeChurchProvider implements IProvider {
  readonly id = "lifechurch";
  readonly name = "Life.Church";

  readonly logos: ProviderLogos = {
    light: "https://cdn.brandfetch.io/idRrA6pM45/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1668042253613",
    dark: "https://cdn.brandfetch.io/idRrA6pM45/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1668042253613"
  };

  readonly config: ContentProviderConfig = {
    id: "lifechurch",
    name: "Life.Church",
    apiBase: "https://open.life.church",
    oauthBase: "",
    clientId: "",
    scopes: [],
    endpoints: {}
  };

  readonly requiresAuth = false;
  readonly authTypes: AuthType[] = ["none"];
  readonly capabilities: ProviderCapabilities = {
    browse: true,
    presentations: true,
    playlist: true,
    instructions: true,
    mediaLicensing: false
  };

  private data: LifeChurchData = lifeChurchData as LifeChurchData;

  private youtubeThumbnail(youtubeId: string): string {
    return `https://i.ytimg.com/vi/${youtubeId}/hqdefault.jpg`;
  }

  private findSeries(seriesId: string): LifeChurchSeries | undefined {
    return this.data.series.find(s => s.id === seriesId);
  }

  private findUnit(series: LifeChurchSeries, unitId: string): LifeChurchUnit | undefined {
    return series.units.find(u => u.id === unitId);
  }

  private findLesson(unit: LifeChurchUnit, lessonId: string): LifeChurchLesson | undefined {
    return unit.lessons.find(l => l.id === lessonId);
  }

  private lessonToFile(lesson: LifeChurchLesson): ContentFile {
    return {
      type: "file",
      id: lesson.id,
      title: lesson.title,
      mediaType: "video",
      url: lesson.videoUrl,
      thumbnail: lesson.thumbnail ?? this.youtubeThumbnail(lesson.youtubeId),
      providerData: { youtubeId: lesson.youtubeId, sourceUrl: lesson.sourceUrl }
    };
  }

  async browse(path?: string | null, _auth?: ContentProviderAuthData | null): Promise<ContentItem[]> {
    const { segments, depth } = parsePath(path);

    if (depth === 0) {
      return this.data.series.map(s => ({
        type: "folder" as const,
        id: s.id,
        title: s.name,
        thumbnail: s.thumbnail,
        path: `/${s.id}`
      }));
    }

    if (depth === 1) {
      const series = this.findSeries(segments[0]);
      if (!series) return [];
      return series.units.map(u => ({
        type: "folder" as const,
        id: u.id,
        title: u.name,
        thumbnail: u.thumbnail ?? series.thumbnail,
        path: `/${series.id}/${u.id}`
      }));
    }

    if (depth === 2) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      if (!series || !unit) return [];
      return unit.lessons.map(l => ({
        type: "folder" as const,
        id: l.id,
        title: l.title,
        thumbnail: l.thumbnail ?? this.youtubeThumbnail(l.youtubeId),
        isLeaf: true,
        path: `/${series.id}/${unit.id}/${l.id}`
      }));
    }

    if (depth === 3) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      const lesson = unit && this.findLesson(unit, segments[2]);
      if (!lesson) return [];
      return [this.lessonToFile(lesson)];
    }

    return [];
  }

  async getPlaylist(path: string, _auth?: ContentProviderAuthData | null, _resolution?: number): Promise<ContentFile[] | null> {
    const { segments, depth } = parsePath(path);

    if (depth === 3) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      const lesson = unit && this.findLesson(unit, segments[2]);
      return lesson ? [this.lessonToFile(lesson)] : null;
    }

    if (depth === 2) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      if (!unit) return null;
      const files = unit.lessons.map(l => this.lessonToFile(l));
      return files.length > 0 ? files : null;
    }

    return null;
  }

  async getInstructions(path: string, _auth?: ContentProviderAuthData | null): Promise<Instructions | null> {
    const { segments, depth } = parsePath(path);

    const buildItem = (lesson: LifeChurchLesson): InstructionItem => ({
      id: `${lesson.id}-action`,
      itemType: "action",
      label: lesson.title,
      actionType: "play",
      children: [
        {
          id: lesson.id,
          itemType: "file",
          label: lesson.title,
          downloadUrl: lesson.videoUrl,
          thumbnail: lesson.thumbnail ?? this.youtubeThumbnail(lesson.youtubeId),
          mediaType: "video"
        }
      ]
    });

    if (depth === 3) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      const lesson = unit && this.findLesson(unit, segments[2]);
      if (!series || !unit || !lesson) return null;
      return { name: lesson.title, items: [{ id: `${unit.id}-section`, itemType: "section", label: unit.name, children: [buildItem(lesson)] }] };
    }

    if (depth === 2) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      if (!unit) return null;
      return { name: unit.name, items: [{ id: `${unit.id}-section`, itemType: "section", label: unit.name, children: unit.lessons.map(buildItem) }] };
    }

    return null;
  }

  supportsDeviceFlow(): boolean {
    return false;
  }
}
